---
- name: Install Nginx and Prometheus-nginx-exporter
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present

- name: Copy Nginx configuration for uWSGI frontend
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: 
    - Restart Nginx
    - Restart Prometheus

- name: Ensure Nginx is started and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Prometheus-nginx-exporter is started and enabled on boot
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
