---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy Nginx configuration for uWSGI frontend
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  notify: Restart Nginx

- name: Ensure Nginx is started and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Flush handlers to ensure Nginx is restarted before installing the exporter
  meta: flush_handlers

- name: Install Nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: present

- name: Ensure Prometheus-nginx-exporter is started and enabled on boot
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
