- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present

- name: Deploy uWSGI config for AGAMA
  ansible.builtin.copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0644'
  notify: Restart uWSGI

- name: Ensure uWSGI service is running
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
