---
- name: Initial setup
  hosts: all
  roles:
    - init
    
- name: DNS servers
  hosts: dns_servers
  roles:
    - bind
    
- name: Resolver
  hosts: all
  roles: 
    - resolver

- name: Prometheus server
  hosts: prometheus
  roles:
    - prometheus
    - nginx
    
- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: InfluxDB server
  hosts: influxdb
  roles:
    - influxdb

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
    
- name: Grafana server
  hosts: grafana
  roles:
    - grafana

- name: Agama client
  hosts: agama_clients
  roles:
    - agama_client