---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags:
    - init
    
- name: DNS servers
  hosts: dns_servers
  roles:
    - bind
  tags:
    - dns
    
- name: Resolver
  hosts: all
  roles: 
    - resolver
  tags: 
    - resolver

- name: Prometheus server
  hosts: prometheus
  roles:
    - prometheus
    - nginx
  tags:
    - prometheus
    
- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - mx

- name: InfluxDB server
  hosts: influxdb
  roles:
    - influxdb
  tags:
    - influxdb

- name: Keepalived
  hosts: keepalived
  roles: 
    - keepalived
  tags:
    - keepalived
  
- name: Haproxy
  hosts: haproxy
  roles:
    - haproxy
  tags:
    - haproxy

- name: Web server
  hosts: web_servers
  roles:
    - docker
    - agama
    - nginx
  tags:
    - mx
    
- name: Grafana server
  hosts: grafana
  roles:
    - docker
    - nginx
    - grafana
  tags:
    - grafana

- name: Agama client
  hosts: agama_clients
  roles:
    - agama_client
  tags:
    - agama_client