{
 "title": "Backups",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Last MySQL backup time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"Maceri1\", service=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "incremental MySQL backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Maceri1\", service=\"mysql\", type=\"incremental\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Full backups for MySQL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Maceri1\", service=\"mysql\", type=\"full\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last InfluxDB backup time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"Maceri1\", service=\"influxdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incremental InfluxDB backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Maceri1\", service=\"influxdb\", type=\"incremental\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Full InfluxDB backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Maceri1\", service=\"influxdb\", type=\"full\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}