{
 "title": "MySQL",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "MySQL Server ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL status + amount of selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Read Only Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Replication SQL Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Replication IO Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}