---
- name: Restart Bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Restart Bind Exporter
  ansible.builtin.systemd:
    name: prometheus-bind-exporter
    state: restarted
    