---
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

#- name: Restart Prometheus
 # ansible.builtin.systemd:
  #  name: prometheus-nginx-exporter
   # state: restarted