- name: Make keepalived directory
  ansible.builtin.file:
    path: /etc/keepalived/
    state: directory

- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Create user keepalived script
  ansible.builtin.user:
    name: keepalived_script
    state: present

- name: Move Keepalived script
  ansible.builtin.template:
    src: keepalived_script.sh
    dest: /home/keepalived_script/keepalived_script.sh 
    mode: '0744'
    owner: keepalived_script

- name: Move Keepalived template
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  no_log: true
  notify: Restart Keepalived

- name: Make sure Keepalaived is running
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true

- name: Download Keepalive exporter package
  ansible.builtin.get_url:
    url: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /home/keepalived_script/

- name: Install Keepalived exporter package
  ansible.builtin.unarchive:
    src: /home/keepalived_script/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true

- name: Move Keepalived service
  ansible.builtin.template:
    src: keepalived-exporter.service
    dest: /etc/systemd/system/
    mode: '0644'

- name: Start Keepalived service
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: true