- name: Install agama client dependencies
  ansible.builtin.apt:
    name:
      - fping
    state: present

- name: Create agama-client user
  ansible.builtin.user:
    name: agama-client
    system: yes
    create_home: yes

- name: Place agama-client script
  ansible.builtin.template:
    src: agama-client.j2
    dest: /usr/local/bin/agama-client
    mode: '0755'

- name: Create agama-client config directory
  ansible.builtin.file:
    path: /etc/agama-client
    state: directory
    mode: '0755'

- name: Place agama-client config
  ansible.builtin.template:
    src: agama-client.conf.j2
    dest: /etc/agama-client/agama-client.conf
    mode: '0644'

- name: Create agama-client systemd service
  ansible.builtin.template:
    src: agama-client.service.j2
    dest: /etc/systemd/system/agama-client.service
    mode: '0644'
  notify: Reload systemd

- name: Ensure agama-client service is started and enabled
  ansible.builtin.service:
    name: agama-client
    state: started
    enabled: yes