- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Python Docker library
  apt:
    name: python3-docker
    state: present

- name: Ensure Docker is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes