# roles/init/tasks/main.yml

#- name: Ansible ping module
#  ansible.builtin.ping:

#- name: Create user juri
#  ansible.builtin.user:
#    name: juri
#    state: present
#    create_home: yes

#- name: Create user roman
#  ansible.builtin.user:
#    name: roman
#    state: present
#    create_home: yes

#- name: Juri SSH
#  ansible.builtin.authorized_key:
#    user: juri
#    state: present
#    key: "{{ lookup('url', 'https://github.com/hudolejev.keys') }}"

#- name: Roman SSH
#  ansible.builtin.authorized_key:
#    user: roman
#    state: present
#    key: "{{ lookup('url', 'https://github.com/romankuchin.keys') }}"
    
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Install Rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: present
    
- name: Ensure that Rsyslog is running
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
    
- name: Configure rsyslog to send logs to Telegraf
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
    mode: '0644'
  notify: Restart Rsyslog